server:
  port: 8090

spring:
  application:
    name: harmonia
  devtools:
    add-properties: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/harmonia_db}
    username: ${SPRING_DATASOURCE_USERNAME:harmonia}
    password: ${SPRING_DATASOURCE_PASSWORD:harmonia}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    user:
      name: user
      password: harmonia


springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    deep-linking: true
    doc-expansion: list
  writer-with-order-by-keys: true


